tree:
    git ls-files | tree --fromfile --dirsfirst

pylint:
    pylint poema_top/ --max-line-length 120 || :

mypy:
    mypy -p poema_top --strict || :

treina:
    python3 -m poema_top.treina

amostra:
    python3 -m poema_top.amostra

infere:
    python3 -m poema_top.infere

websocket:
    xdg-open poema_top/websocket/index.html
    python3 -m poema_top.websocket
